Dylann
JimmyC7834/U.stick-battle-arena pull request #26
Opened 2023-02-11 06:08 UTC by dylannalcock

Finished the main menu, need to link start button to game scene still.

2023-02-11 06:45 UTC, JimmyC7834 commented
@dylannalcock there's no menu in the menu scene. The scene is empty.

2023-02-11 06:49 UTC, JimmyC7834 commented on Assets/UI/Menu Scripts/MenuScript.cs
> +using System.Collections;
What is this folder and script for? they are all empty

2023-02-11 06:49 UTC, JimmyC7834 commented on Assets/UI/MenuParticles/Particle/particle1.mat
> +%YAML 1.1
What is the use of the particle thing? What are they used for? I don't see any use cases in your changes

2023-02-11 06:49 UTC, JimmyC7834 commented
@dylannalcock  Please also put all the script under the script folder, prefab under the prefab folder, etc.

2023-02-11 07:22 UTC, Teru5244 requested changes
In my perspective your PR is incomplete or even empty, please finish the implementation and address the problems proposed by Jimmy above before PR them.

2023-02-12 03:04 UTC, JimmyC7834 approved these changes

2023-02-12 03:27 UTC, Teru5244 approved these changes

2023-02-12 03:28 UTC, merged

2023-02-12 04:45 UTC, JimmyC7834 reviewed
@dylannalcock please review your mistakes and don't it them next time

2023-02-12 04:45 UTC, JimmyC7834 commented on Assets/Scripts/MenuScript.cs
> +    public string firstLevel;
We should always make private variables
This is not following the naming scheme please goto read the C# style guide in our repo's root folder

2023-02-12 04:45 UTC, JimmyC7834 commented on Assets/Scripts/MenuScript.cs
> +    void Start()
Remove empty functions

2023-02-12 04:45 UTC, JimmyC7834 commented on Assets/Scripts/MenuScript.cs
> +    void Update()
Remove empty functions

2023-02-12 04:45 UTC, JimmyC7834 commented on Assets/Scripts/MenuScript.cs
> +    public void PlayGame() {
Not following style guide, we do it like this:
```
public void PlayGame()
{
...
}
```

2023-02-12 04:45 UTC, JimmyC7834 commented on Assets/Scripts/MenuScript.cs
> +public class MenuScript : MonoBehaviour
All of our script should be in the `Game` namespace